### PR TITLE
Added option to output fish shell commands to stdout

### PR DESCRIPTION
**Pull request by Copperis**
Pretty much the title.

Also refactored the logic to a switch statement + constants. I don't know the best practices for this, but seems fine.

Thanks for the application!

### CODE REVIEW

**Comment by cuviper** [comment]
Ugh, fish had to go and be different.  Well, I'm open to a new option, but I don't like `-f` for this.  That's often the option letter for forcing an operation, which we don't need yet here, but I'd rather leave it open.

How about breaking that `SHELL` one-liner into a new function to scan for fish/csh/sh, and then add a `-S shell` option to also call that?  Then we can add arbitrary new shells without taking up more option letters.

I'd use an enum with implicit values rather than your explicit defines, but otherwise your approach looks fine.  Maybe put the set/unset switches into new functions too, near the parsing function.

Documentation in `README.md` and `ssh-pageant.1` also need updates for the new option.

**Comment by Copperis** [comment]
Thanks for the suggestions. I have updated the pull request.

Please check if there's anything else that can be improved.

**Comment by cuviper** [comment]
I meant for you to add a new `-S` option, capitalized.  I don't want to change the existing behavior of `-c` and `-s`, as those are supposed to correspond to `ssh-agent` options.

Why are your env functions taking all pointers?  That only makes sense for the sockpath - the rest should just be values.

**Comment by Copperis** [comment]
Changed the option to `-S` and added `-s` and `-c` back in. 
> Why are your env functions taking all pointers? That only makes sense for the sockpath - the rest should just be values.

I don't do a lot of C programming and might not understand something here. What is the point of copying values for the functions when you can pass in pointers to already existing values?

**Comment by cuviper** [comment]
A pointer is just a value of a different sort, and it adds indirection.
For things like enum and int, those values are smaller and no more
expensive to copy than the pointer value.

It's not really much of a performance concern here either way.  An
optimizing compiler will almost surely inline these functions and skip the
pointers.  And this isn't a performance hotspot anyway, just called once
for initialization.  So it's more about the cognitive load to the
programmer, where the pointer in this case is an unnecessary complication.

**Comment by Copperis** [comment]
Right, pointer addresses get copied too. I have updated the pull request.

**Comment by cuviper** [comment]
Thanks!

I made the docs more terse, as I think that's easier to scan, and I also want it to look nice on 80-char wide terminals.  I also changed `-S c` to `-S csh` and made unrecognized shells an error.

**Pull request merged**
